### ISSUE TITLE
Microsoft Login issue

### ISSUE THREAD

**Issue by yundanielone** [ansible-lockdown/Windows-10-STIG#21]
After applying the STIG's, I've been unable to get Windows Update, Microsoft Store, or Office logins to connect. It seems like it is unable to connect to any Microsoft servers it needs to.  I've done some Googling and extensive testing with a test machine to narrow it down that a STIG requirement is breaking the connection.
Before I go through each STIG to figure out what is breaking it, I was wondering if anyone knows which STIG would be the culprit.
Thanks for your time!

**Comment by MrSteve81** [comment]
I believe one of your issues is a CAT 3 control WN10-CC-000206 for the updates.

**Comment by yundanielone** [comment]
Thank you for the response!
I looked up your suggestion and it seems to have had no effect.
I will continue going through one by one and hopefully get it resolved.
Thank you again!

**Comment by yundanielone** [comment]
Just wanted to update this. After combing through the STIG's, it was found to be V-220805 version WN10-CC-000052.
Solution:
- Open regedit
- Make a backup of keys if necessary
- Registry Path: HKLM\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002
- Delete Value Name: EccCurves
- Reboot

I believe the value for EccCurves could also be modified to work, but haven't had a chance to test that yet.

**Comment by MrSteve81** [comment]
Thanks for the feedback and i will also take a look at this as well.
